---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: [ "*" ]
        update-types: [ "major", "minor", "patch" ]
